javabrains/javasikho/urls.py
from django.contrib import admin
from django.conf.urls import url
from javasikhoApp import views
from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name = 'index'),
    url(r'^topics/',include('javasikhoApp.urls')),

]

javabrains/javasikhoApp/urls.py
from django.conf.urls import url,include
from javasikhoApp import views
app_name = 'javasikhoApp'
urlpatterns = [
    url(r'^$',views.topics,name='topics'),
    url(r'^Learn/(?P<sub>[0-9A-Za-z_\-]+)/$',views.java,name='Learn'),
    #url(r'^ (?P<language>w+)/$',views.list_topics,name='list_topics'),
]

javabrains/javasikhoApp/models.py
from django.db import models



class Topics(models.Model):
    Sub = models.CharField(max_length =128)
    Title = models.CharField(max_length =128)
    Link = models.CharField(max_length =256 , unique = True)
# Create your models here.

javabrains/javasikhoApp/views.py

from django.shortcuts import render
from django.http import HttpResponse
from javasikhoApp.models import Topics

# Create your views here.
def index(request):
    return render(request, 'javasikhoApp/index.html')
# Create your views here.
def topics(request):

    #get distinct topics from
    context ={}
    f_topics = Topics.objects.values_list('Sub').distinct()
    topics=[]
    for topic in f_topics:
        topics.append(topic[0])
        context={"topics":topics}
    return render(request,'javasikhoApp/topics.html',context=context)

def java(request,sub):
    link_list = Topics.objects.filter(Sub = sub)
    link_dict = {"topics":link_list}
    return render(request,'javasikhoApp/Learn.html', context=link_dict)

def list_topics(request, language):
    link_list = Topics.objects.filter(Sub =language)
    link_dict = {"topics":link_list}
    return render(request,'javasikhoApp/Learn.html', context=link_dict)

javabrains/templates/javasikhoApp/Learn.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

    <body>

      {% if topics %}

      <ol>
<h1> Topics Info </h1>

         {% for Subj in topics %}

         <ul>

           <li>{{Subj.Sub}} : {{Subj.Title}} :<a href = {{Subj.Link}}>{{Subj.Link}}</a></li>



        </ul>
        {% endfor %}

      </ol>
      {% endif %}
    </body>

</html>

javabrains/templates/javasikhoApp/index.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}
.menu {
  float:left;
  width:20%;
  text-align:center;
}
.menu a {
  background-color:Violet;
  padding:8px;
  margin-top:7px;
  display:block;
  width:100%;
  color:black;
}
.main {
  float:left;
  width:60%;
  padding:0 20px;
}
.fixed-header, .fixed-footer{
        width: 100%;
        position: fixed;
        background: #333;
        padding: 10px 0;
        color: #fff;
        text-align:center
    }
    .fixed-footer{
        bottom: 0;
    }
.right {
  background-color:#e5e5e5;
  float:left;
  width:20%;
  padding:15px;
  margin-top:7px;
  text-align:center;
}

@media only screen and (max-width:620px) {
  /* For mobile phones: */
  .menu, .main, .right {
    width:100%;
  }
}
</style>
</head>
<body style="font-family:Verdana;color:#000000;">

<div style="background-color:Tomato;padding:15px;text-align:center;">
  <h1>Java Brains Home Page Learning</h1>
</div>

<div style="overflow:auto">
  <div class="menu">
    <a href = "http://127.0.0.1:8000/topics">Topics </a>

  </div>

  <div class="main">
    <h2>Learning Django</h2>
    <p>Learn Java and Python through
hundreds of training videos and learning material</p>
  </div>

  <div class="right">
    <h2>About</h2>
    <p>It's part of task</p>
  </div>
</div>

</div>
   <div class="fixed-footer">
       <div class="container">Copyright Type Anything</div>
   </div>

</body>
</html>

javabrains/templates/javasikhoApp/topics.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style>
    * {
      box-sizing: border-box;
    }

    .menu {
      float:left;
      width:20%;
      text-align:center;
    }
    .menu a {
      background-color:Violet;
      padding:8px;
      margin-top:7px;
      display:block;
      width:100%;
      color:black;
    }
    .main {
      float:left;
      width:60%;
      padding:0 20px;
    }
    .fixed-header, .fixed-footer{
            width: 100%;
            position: fixed;
            background: #333;
            padding: 10px 0;
            color: #fff;
            text-align:center
        }
        .fixed-header{
        top: 0;
    }
        .fixed-footer{
            bottom: 0;
        }
    .right {
      background-color:#e5e5e5;
      float:left;
      width:20%;
      padding:15px;
      margin-top:7px;
      text-align:center;
    }

    @media only screen and (max-width:620px) {
      /* For mobile phones: */
      .menu, .main, .right {
        width:100%;
      }
    }
    </style>
    <meta charset="utf-8">
    <title></title>
  </head>

<body style="font-family:Verdana;color:#000000;">

  <div style="background-color:Tomato;padding:15px;text-align:center;">
    <h1>Listed Topics are : {{topics}} </h1>

  </div>

  <div style="overflow:auto">
    <div class="menu">
    <ul>
      {% for topic in topics%}
  <ol><a href="{% url 'javasikhoApp:Learn' topic %}">Learn {{topic}} </a></ol>
  {%endfor%}
</ul>
</div>
</div>
   <div class="fixed-footer">
       <div class="container">Copyright Type Anything</div>
   </div>

</body>
</html>